services:
  reverse-proxy:
    image: traefik:v3.1
    command:
      - "--api.insecure=true"
      - "--providers.docker"
      # - "--log.level=ERROR"
      # - "--accesslog=true"
      # - "--providers.docker"
      # - "--providers.docker.exposedbydefault=false"
      # - "--entryPoints.websecure.address=:443"
      # - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
      # - "--certificatesresolvers.myresolver.acme.email=elliott@zenful.cloud"
      # - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
      # - "--entrypoints.web.address=:80"
      # - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
      # - "--entrypoints.web.http.redirections.entrypoint.scheme=https"
      # - "--entryPoints.web.forwardedHeaders.insecure"
      # - "--entryPoints.websecure.forwardedHeaders.insecure"
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      # - letsencrypt:/letsencrypt
      - /var/run/docker.sock:/var/run/docker.sock
  website:
    image: ghcr.io/moxcz/personal-website
    labels:
      - "traefik.http.routers.website.rule=Host(`mocosmo.me`)"
      # - "traefik.enable=true"
      # - "traefik.http.middlewares.guestbook-ratelimit.ratelimit.average=20"
      # - "traefik.http.routers.website.rule=Host(`mocosmo.me`) && !Method(`POST`)"
      # - "traefik.http.routers.website.entrypoints=websecure"
      # - "traefik.http.routers.website.tls.certresolver=myresolver"
      # - "traefik.http.routers.website.middlewares=guestbook-ratelimit"
      # Define separate router for POST methods
      # - "traefik.http.middlewares.website-ratelimit-post.ratelimit.average=1"
      # - "traefik.http.middlewares.website-ratelimit-post.ratelimit.period=1m"
      # - "traefik.http.routers.website-post.rule=Host(`mocosmoe.me`) && Method(`POST`)"
      # - "traefik.http.routers.website-post.middlewares=guestbook-ratelimit-post"
      # - "traefik.http.routers.website-post.entrypoints=websecure"
      # - "traefik.http.routers.website-post.tls.certresolver=myresolver"
      # Proxy
      # - "traefik.http.routers.proxy.rule=Host(`proxy.dreamsofcode.io`)"
      # - "traefik.http.routers.proxy.entrypoints=websecure"
      # - "traefik.http.routers.proxy.tls.certresolver=myresolver"
      # Enable watchtower
      # - "com.centurylinklabs.watchtower.enable=true"
    container_name: personal-website
